version: "3.9"  # optional since v1.27.0
services:
  myReactApp:
    image: react-app
    # command: "npm install && nmp start"
    ports:
      - "3000:3000"
    volumes:
      - ./app/src:/app/react_app/src
      - ./app/public:/app/react_app/public
#       - bind-test:/app/react_app
# volumes:
#   bind-test:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /home/alex/REACT/learn-react-uibi/volume